# Generated by Django 5.0 on 2024-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_rename_deadline_todo_dealine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="dealine",
            field=models.DateField(),
        ),
    ]
